---
spring:
    profiles: default
server:
    port: 8760
eureka:
    instance:
        hostname: localhost-com
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'
---
spring:
    profiles: us
    application:
        name: eureka-server
server:
    port: 8761
eureka:
    instance:
        hostname: localhost-us
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: 'http://localhost-fr:8762/eureka/,http://localhost-vn:8763/eureka/'
---
spring:
    profiles: fr
    application:
        name: eureka-server
server:
    port: 8762
eureka:
    instance:
        hostname: localhost-fr
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: 'http://localhost-us:8761/eureka/,http://localhost-vn:8763/eureka/'
---
spring:
    profiles: vn
    application:
        name: eureka-server
server:
    port: 8763
eureka:
    instance:
        hostname: localhost-vn
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: 'http://localhost-us:8761/eureka/,http://localhost-fr:8762/eureka/'
