spring:
    profiles: us
    application:
        name: LOCALHOSTUS

server:
    port: 8761

eureka:
    instance:
        hostname: localhost-us
        appname: LOCALHOSTUS
    client:
        registerWithEureka: true
#        fetchRegistry: true
        serviceUrl:
#            defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'
            defaultZone: 'http://localhost-fr:8762/eureka/,http://localhost-vn:8763/eureka/,http://localhost-en:8764/eureka/'
#    server:
#        enableSelfPreservation: false
